<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

<hr>

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=2463&pageid=4531&startlastseen=no"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/2-DAwPY/DAwPy_S01_(Numpy_Arrays).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="90" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DAwPy_S1_%28Numpy_Arrays%29/DAwPy_S1_%28Numpy_Arrays%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="100" height="100" title="Open and Execute in nbviewer"></a><br/>

<hr>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="500" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/XS0bxSH/best-bootcamps.png" width="300" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY_Courses"></p>

<img src=https://i.ibb.co/8NdjfdZ/Num-Py-logo.png width="500" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Session - 02</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#E51A59; font-size:150%; text-align:center; border-radius:10px 10px;">Numpy Arrays (Part-02)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [IMPORTING LIBRARIES NEEDED IN THIS NOTEBOOK](#0)
* [CONCATENATION OF THE ARRAYS](#00)
    * [2D Matrix](#00.1)
* [SPLITTING OF THE ARRAYS](#000)
    * [2D Matrix](#000.1)
* [SORTING OF THE ARRAYS](#0000)
    * [2D Matrix](#0000.1)
* [NUMPY INDEXING & SELECTION](#1)
    * [Bracket Indexing & Selection](#1.1)
    * [Indexing a 2D Array (Matrices)](#1.2)
    * [Slicing a 2D Array (Matrices)](#1.3)
    * [Fancy Indexing](#1.4)
    * [Using Basic Index & Fancy Index Together](#1.5)
    * [Using Basic Slicing & Fancy Index Together](#1.6)
    * [More Indexing Help](#1.7)
* [SELECTION ON A CONDITION](#2)
* [BROADCASTING](#3)
* [NUMPY OPERATIONS](#4)
    * [Arithmetic Operations](#4.1)
    * [Universal Array Functions](#4.2)
    * [Statistical Calculations](#4.3)
* [OFFICIAL TUTORIAL](#5)
* [THE END OF THE SESSION-02](#6)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Importing Libraries Needed in This Notebook</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Once you've installed NumPy you can import it as a library:

**``NOTE:``** For installation instructions, please refer to the notebook at SESSION-01 (Numpy Part-01)

In [2]:
import numpy as np

**🔔🔔🔔 REMINDER**<br>
NumPy or Numeric Python is a package for computation on homogenous n-dimensional arrays. In numpy dimensions are called as axes.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists. The array object in NumPy is called ndarray , it provides a lot of supporting functions that make working with ndarray very easy. Arrays are very frequently used in data science, where speed and resources are very important.

- NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further

**🧐 [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)**

**📌 Why do we need NumPy?**

- A question arises that why do we need NumPy when python lists are already there. The answer to it is we cannot perform operations on all the elements of two list directly (Remember the concept of "Vectorization" from our previous session). For example, we cannot multiply two lists directly we will have to do it element-wise. This is where the role of NumPy comes into play.

**📌 2 important concepts in Numpy:**

- **``Vectorization``** and **``Broadcasting``** are ways to speed up the compute time and optimize memory usage while doing mathematical operations with Numpy. These methods are crucial to ensure time complexity is reduced so that the algorithms don't face any bottlenecks.

**🧐 [Vectorization and Broadcasting in Python](https://www.upgrad.com/blog/vectorization-and-broadcasting-in-python/#:~:text=Vectorization%20and%20Broadcasting%20are%20ways,don't%20face%20any%20bottlenecks)**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Concatenation of the Arrays</p>

<a id="00"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

- In this lecture we will first discuss how to concatenate, split and sort the arrays.

  - **``concatenate((a1, a2, ...), axis=0, out=None)``**
  
<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>Concatenation of two 1D Numpy Arrays Along an Axis:</strong></p>


<p style="text-align: center;"><img src="https://i.ibb.co/FYfgqz7/concat-of-1-Darray.png" width="300" height="200" class="img-fluid" alt="concat-of-1-Darray"></p>


[Image Credit: Kanopi.org](https://kanoki.org/2020/01/10/concatenating-arrays-in-numpy/)

In [3]:
# We’ve created three NumPy arrays: x, y, and z

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

In [4]:
display(x)
display(y)

np.concatenate([x, y])  # concatenates two or more one-dimensional arrays.

array([1, 2, 3])

array([4, 5, 6])

array([1, 2, 3, 4, 5, 6])

<div style="display: flex; justify-content: left; gap: 20px;">
    <img src="https://i.ibb.co/L1PXSQp/axis-0-1.png" width="400" height="200" alt="axis-0-1">
    <img src="https://i.ibb.co/KyRLYy8/dimensions-in-array.png" width="400" height="200" alt="dimensions-in-array">
</div>

<!-- <p style="text-align: center;"><img src="https://i.ibb.co/L1PXSQp/axis-0-1.png" width="400" height="200" class="img-fluid" alt="axis-0-1"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/KyRLYy8/dimensions-in-array.png" width="400" height="200" class="img-fluid" alt="dimensions-in-array"></p> -->

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 From the NumPy documentation: The arrays you want to concatenate need to be passed in as a SEQUENCE, NOT as separate arguments.</strong></p>

**[NumPy documentation](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html)**

In [5]:
# The default axis value is 0. That is, in single dimensions, it combines along axis=0.

np.concatenate([x, y, z], axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# np.concatenate([x, y, z], axis=1) # gives an error

AxisError: axis 1 is out of bounds for array of dimension 1

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 The error occurs because np.concatenate requires that the arrays have compatible shapes along the specified axis. In your case, x, y, and z are 1-dimensional arrays, and we are trying to concatenate them along axis=1, which is NOT valid for 1D arrays.</strong></p>

In [10]:
# Print the shapes of the arrays

print(x.shape)
print(y.shape)
print(z.shape)

(3,)
(3,)
(3,)


### Reshaping these arrays to 2D allows us to concatenate them along axis=1 without any issues. 


In [8]:
# Reshape the arrays to (1, 3) and concatenate along axis 1
# x.reshape(1, 3) changes the shape of x from (3,) to (1, 3), making it a row vector.

display(np.concatenate([x.reshape(1, 3), y.reshape(1, 3), z.reshape(1, 3)], axis=0))
np.concatenate([x.reshape(1, 3), y.reshape(1, 3), z.reshape(1, 3)], axis=1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 In the context of reshaping an array with NumPy, specifying 1 as a dimension means that we want that dimension to have a size of 1. This is often used to create a column vector or a single-row structure. </strong></p>

- **``1``**: Specifies that the dimension should have a size of 1, which is useful for creating single-column (or single-row) structures.
- This is often done to prepare data for matrix operations, where the shape of the arrays needs to conform to certain requirements.

In [9]:
# Print shapes
print(x.shape)
print(x.reshape(1, 3).shape)
print(x.reshape(-1, 1).shape)

# Reshape the arrays to (3, 1) and concatenate along axis 0 and axis 1
# Concatenate as column vectors. Each array is reshaped to a column vector (3, 1).
display(np.concatenate((x.reshape(-1, 1), y.reshape(-1, 1), z.reshape(-1, 1)), axis=0))
np.concatenate((x.reshape(-1, 1), y.reshape(-1, 1), z.reshape(-1, 1)), axis=1)

(3,)
(1, 3)
(3, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 NumPy calculates the first dimension intiutively based on the total number of elements !!!</strong></p>

- The **``-1``** tells NumPy to **``infer the appropriate size for that dimension based on the total number of elements``** in the array and the specified dimensions.
- In this case, since we are reshaping a 1D array of size 3 into a shape of (?, 1), NumPy calculates that the first dimension must be 3 to maintain the total number of elements (which is 3).

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="00.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

A **``2D matrix``** is a **``rectangular arrangement of numbers or elements``** organized in rows and columns, where each element can be accessed using two indices: 
- one for the row and 
- one for the column. 

This structure allows for various mathematical operations, such as addition, subtraction, and multiplication, as well as applications in fields like computer graphics, data analysis, and machine learning.

<div style="display: flex; justify-content: left; gap: 20px;">
    <img src="https://i.ibb.co/L1PXSQp/axis-0-1.png" width="400" height="200" alt="axis-0-1">
    <img src="https://i.ibb.co/KyRLYy8/dimensions-in-array.png" width="400" height="200" alt="dimensions-in-array">
</div>

In [11]:
# Create two 2D matrices of shape (2, 3) with random integers

a = np.random.randint(10, size=(2, 3))  # Random integers from 0 to 9 and 2 rows and three columns
b = np.random.randint(10, size=(2, 3))  # Random integers from 0 to 9 and 2 rows and three columns

In [12]:
a, b

(array([[0, 2, 9],
        [0, 8, 5]]),
 array([[2, 5, 1],
        [4, 9, 6]]))

In [13]:
display(a)
display(b)

# Concatenate the arrays along the default axis (axis=0)
np.concatenate([a, b])

array([[0, 2, 9],
       [0, 8, 5]])

array([[2, 5, 1],
       [4, 9, 6]])

array([[0, 2, 9],
       [0, 8, 5],
       [2, 5, 1],
       [4, 9, 6]])

<div style="display: flex; justify-content: left; gap: 20px;">
    <img src="https://i.ibb.co/c3cFkDb/explanation-numpy-concatenate-axis-0.png" width="400" height="170" alt="oncatenate-axis-0">
    <img src="https://i.ibb.co/KyRLYy8/dimensions-in-array.png" width="400" height="200" alt="dimensions-in-array">
</div>

**[How to use the NumPy concatenate function](https://www.sharpsightlabs.com/blog/numpy-concatenate/)**

In [14]:
display(a)
display(b)

# Concatenate the matrices along the axis=1
np.concatenate([a, b], axis=1)

array([[0, 2, 9],
       [0, 8, 5]])

array([[2, 5, 1],
       [4, 9, 6]])

array([[0, 2, 9, 2, 5, 1],
       [0, 8, 5, 4, 9, 6]])

<div style="display: flex; justify-content: left; gap: 20px;">
    <img src="https://i.ibb.co/x7HmxJP/explanation-numpy-concatenate-axis-1.png" width="350" height="200" alt="oncatenate-axis-1">
    <img src="https://i.ibb.co/KyRLYy8/dimensions-in-array.png" width="400" height="200" alt="dimensions-in-array">
</div>

**[How to use the NumPy concatenate function](https://www.sharpsightlabs.com/blog/numpy-concatenate/)**

<hr>

**The following code creates two 2D NumPy arrays, x and y, and prints their shapes.**

In [15]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

x, y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]))

In [16]:
# Concatenate the arrays along axis 0. This means that the arrays are stacked vertically

display(x)  # both x and y have 3 columns
display(y)  # both x and y have 3 columns

np.concatenate([x, y], axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

array([[ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

### 🔥 Be Noted: 🔥

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 All the input array dimensions for the concatenation axis MUST match exactly. The number of columns or rows MUST match❗❗❗</strong></p>

- You CANNOT concatenate arrays with different numbers of rows along axis=1.
- You can either pad the smaller array or trim the larger array to match their dimensions.

<img src="https://i.ibb.co/DCW2Mhr/concat-of-1-Darray1.png" alt="Numpy Concatenation">

<p><a href="https://kanoki.org/2020/01/10/concatenating-arrays-in-numpy/">Image Credit: Kanopi.org</a></p>

In [17]:
# np.concatenate([x,y], axis=1) # it gives an error

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Splitting of the Arrays</p>

<a id="000"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

- **``np.split(ary, indices_or_sections, axis=0)``**

In [18]:
# Define a one dimensional array
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [19]:
# Split the array at indices 3 and 5 (both exclusive)

np.split(x, [3, 5])  # splits x into three parts: before index 3, between indices 3 and 5, and after index 5.

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

<p style="text-align: center;"><img src="https://i.ibb.co/mSkn0YQ/numpy-array-negative-index.png" width="500" height="200" class="img-fluid" alt="indices-in-array"></p>


**[Image Credit: programiz.com](https://www.programiz.com/python-programming/numpy/array-indexing)**

If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[3, 5]`` would, for ``axis=0``, result in
- ``ary[:3]``
- ``ary[3:5]``
- ``ary[5:]``

In [20]:
# Split the array at indices 3 and 5 and assign them

a, b, c = np.split(x, [3, 5])

In [21]:
a

array([1, 2, 3])

In [22]:
b

array([99, 99])

In [23]:
c

array([3, 2, 1])

In [24]:
display(x)

np.split(x, [4])

array([ 1,  2,  3, 99, 99,  3,  2,  1])

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]

### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 Be Careful in the following:❗❗❗</strong></p>



<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>🔥 It will split the 1D array x into 4 equal parts. However, if the length of x is NOT divisible by 4, NumPy will raise an error because it cannot split the array evenly.🔥</strong></p>


In [25]:
# Attempt to split the array into 4 EQUAL parts

np.split(x, 4)

# # Define split indices for 4 parts
# split_indices = [2, 4, 6]  # This will create 4 parts
# # Split the array at specified indices
# result = np.split(x, split_indices)

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

- The number of the elements ``should be divisible`` by 4, otherwise raises an error. If the argument (here is 4) is not enclosed by square brackets, then it means dividing into 4 pieces.

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="000.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [26]:
# Create a 1D array with values from 0 to 19 and reshape it into a 5x4 matrix
m = np.arange(20).reshape(5, 4)

# Display the matrix
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
# Split the matrix at indices 1 and 3 along axis 0

np.split(m, [1, 3], axis=0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

<div style="display: flex; justify-content: left; gap: 10px;">
    <img src="https://i.ibb.co/L1PXSQp/axis-0-1.png" width="300" height="200" alt="axis-0-1">
    <img src="https://i.ibb.co/mSkn0YQ/numpy-array-negative-index.png" width="400" height="200" alt="indices-in-array">
    <img src="https://i.ibb.co/r0K7LPv/numpy-array-index.png" width="400" height="200" alt="numpy-array-index">
</div>

In [28]:
display(m)

# Split the matrix at indices 1 and 3 (Exclusive) along axis 1
np.split(m, [1, 3], axis=1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [29]:
display(m)

# Vertically split the matrix at indices 1 and 3
np.vsplit(m, [1, 3])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

<div style="display: flex; justify-content: left; gap: 10px;">
    <img src="https://i.ibb.co/L1PXSQp/axis-0-1.png" width="300" height="200" alt="axis-0-1">
    <img src="https://i.ibb.co/mSkn0YQ/numpy-array-negative-index.png" width="400" height="200" alt="indices-in-array">
    <img src="https://i.ibb.co/r0K7LPv/numpy-array-index.png" width="400" height="200" alt="numpy-array-index">
</div>

In [30]:
# Vertically split the matrix at index 3

upper, lower = np.vsplit(m, [3])

In [31]:
upper

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 Be Careful in the following:There is NO Square Bracets❗❗❗</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>🔥 Using np.vsplit(m, 5) will result in an error if the number of rows in m is not divisible by 5. The np.vsplit function is meant to split an array into equal parts based on the specified number of sections, and it requires the number of rows to be divisible by the number of splits.🔥</strong></p>


In [36]:
# Focus on double square brackets. All rows are still 2d-arrays.

# Attempt to vertically split the matrix into 5 parts
np.vsplit(m, 5)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [38]:
display(m)

# Horizontally split the matrix at column index 2

np.hsplit(m, [2])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [39]:
# Horizontally split the matrix at column index 2 abd assign them to two objects

left, right = np.hsplit(m, [2])

In [40]:
display(m)

left

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [41]:
display(m)

right

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Sorting of the Arrays</p>

<a id="0000"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [42]:
# Define a one dimensional array
v = np.array([2, 1, 4, 3, 5])

# Display the array
v

array([2, 1, 4, 3, 5])

In [43]:
# Sort the elements in the array in ascending order

np.sort(v)

array([1, 2, 3, 4, 5])

In [44]:
# Print the original array

v  # There is NO change in the original array

array([2, 1, 4, 3, 5])

### <p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 Be Careful in the following:❗❗❗</strong></p>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>🔥 Using v.sort() will sort the 1D NumPy array in place, meaning that it modifies the original array rather than returning a new sorted array.🔥</strong></p>

In [45]:
# Sort the array in place

v.sort()  # changed inplace

In [46]:
# Print the modified array

v

array([1, 2, 3, 4, 5])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">2d Matrix</p>

<a id="0000.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [47]:
# Create a 3x3 matrix with random integers between 5 and 100
twoD = np.random.randint(5, 100, (3, 3))

# Display the array
twoD

array([[34, 56, 55],
       [75, 49, 11],
       [65, 11, 41]])

<div style="display: flex; justify-content: left; gap: 10px;">
    <img src="https://i.ibb.co/L1PXSQp/axis-0-1.png" width="300" height="200" alt="axis-0-1">
    <img src="https://i.ibb.co/mSkn0YQ/numpy-array-negative-index.png" width="400" height="200" alt="indices-in-array">
    <img src="https://i.ibb.co/r0K7LPv/numpy-array-index.png" width="400" height="200" alt="numpy-array-index">
</div>

In [48]:
# Sort the array along the columns (axis=0)

np.sort(twoD, axis=0)  # the rows are sorted from upper to lower and column by column

array([[34, 11, 11],
       [65, 49, 41],
       [75, 56, 55]])

In [49]:
# Sort the array along the rows (axis=1)

np.sort(twoD, axis=1)  # the columns are sorted from left to right and row by row

array([[34, 55, 56],
       [11, 49, 75],
       [11, 41, 65]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Indexing & Selection</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In this part of the lecture we will discuss how to select elements or groups of elements from an array.

Array indexing is the same as accessing an array element. You can access an array element by referring to its index number. The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc. [SOURCE](https://www.w3schools.com/python/numpy/numpy_array_indexing.asp)

### ``Types of Indexing``

There are **``two types of indexing:``**

**``1 - Basic Slicing and indexing:``** Consider the syntax x[obj] where x is the array and obj is the index. Slice object is the index in case of basic slicing. Basic slicing occurs when obj is :
- a slice object that is of the form start : stop : step
- an integer
- or a tuple of slice objects and integers

**``2 - Advanced indexing:``** Advanced indexing is triggered when obj is –

- an ndarray of type integer or Boolean
- or a tuple with at least one sequence object
- is a non tuple sequence object

For more information, please visit [INDEXING SOURCE](https://www.geeksforgeeks.org/numpy-indexing/)


[INDEXING & SLICING Source 01](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html),
[INDEXING & SLICING Source 02](https://www.kite.com/python/answers/how-to-select-an-element-by-index-from-a-numpy-array-in-python),
[INDEXING & SLICING Source 03](https://numpy.org/doc/stable/reference/arrays.indexing.html),
[INDEXING & SLICING Source 04](https://www.pluralsight.com/guides/working-numpy-arrays-indexing-slicing-guide),
[INDEXING & SLICING Source 05](https://www.brainstobytes.com/hands-on-numpy-iii-indexing-and-slicing/),
[INDEXING & SLICING Source 06](https://pandas.pydata.org/pandas-docs/version/1.2.4/user_guide/indexing.html),
[INDEXING & SLICING Source 07](https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm),
[INDEXING & SLICING Source 08](https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d),
[INDEXING & SLICING Video Source 01](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/),
[INDEXING & SLICING Video Source 02](https://www.youtube.com/watch?v=9nbBTaz2qXI),
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=9nbBTaz2qXI) &
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=E1OFcMnU40o)

In [50]:
# Create a 1D array with values from 0 to 10

arr = np.arange(0, 11)

In [51]:
# Display the array

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Bracket Indexing & Selection</p>

<a id="1.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<div style="display: flex; justify-content: left; gap: 10px;">
    <img src="https://i.ibb.co/L1PXSQp/axis-0-1.png" width="300" height="200" alt="axis-0-1">
    <img src="https://i.ibb.co/mSkn0YQ/numpy-array-negative-index.png" width="400" height="200" alt="indices-in-array">
    <img src="https://i.ibb.co/r0K7LPv/numpy-array-index.png" width="400" height="200" alt="numpy-array-index">
</div>

The simplest way to pick one or some elements of an array looks very similar to python lists:

In [52]:
# Access the element (value) at index 8

arr[8]

8

In [53]:
# Negative indexing works like in python lists
# Access the last element using negative indexing

arr[-1]

10

In [54]:
# Get values in a range
# Slice the array from index 1 to 5

arr[1:5]

array([1, 2, 3, 4])

In [55]:
# Get values in a range
# Slice the array from the start up to index 5

arr[:5]

array([0, 1, 2, 3, 4])

In [56]:
# Let's remember our array

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
# arr[start:stop:step], accesing odd numbers in this case
# Slice the array starting from index 1, taking every second element

arr[1::2]

array([1, 3, 5, 7, 9])

In [58]:
# arr[start:stop:step], accesing even numbers in this case
# Slice the array starting from index 0, taking every second element

arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Indexing a 2D Array (Matrices)</p>

<a id="1.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row, col]</b>.<br>
It's usually recommended using the comma notation for clarity.</p>

<!-- ![image.png](https://i.ibb.co/pvdHbBm/numpy-index.png)

![image-2.png](https://i.ibb.co/jJPp6hk/numpy-indexing2.png) -->


<div style="display: flex; justify-content: left; gap: 10px;">
    <img src="https://i.ibb.co/pvdHbBm/numpy-index.png" width="300" height="200" alt="axis-0-1">
    <img src="https://i.ibb.co/jJPp6hk/numpy-indexing2.png" width="400" height="200" alt="indices-in-array">
</div>

[SOURCE01](https://www.google.com/url?sa=i&url=https%3A%2F%2Fmedium.com%2F%40msjahid%2Fnumpy-array-indexing-slicing-23b70abb8433&psig=AOvVaw2ETiXFpQ-F-d0CMV8jD1dJ&ust=1644053862804000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCIDj5JXg5fUCFQAAAAAdAAAAABAk), [SOURCE02](https://www.google.com/url?sa=i&url=https%3A%2F%2Fiq.opengenus.org%2F2d-array-in-numpy%2F&psig=AOvVaw2ETiXFpQ-F-d0CMV8jD1dJ&ust=1644053862804000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCIDj5JXg5fUCFQAAAAAdAAAAABAp)<br>

In [59]:
# Create a 2D array  with values in a nested list
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

# Display the array
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
# Indexing row
# Access the second row (index 1)

arr_2d[1]

array([20, 25, 30])

In [61]:
# Format is arr_2d[row][col] or arr_2d[row, col]

# Getting individual element value
# Access the element at row index 1 and column index 2
arr_2d[1][2]

30

In [62]:
# Getting individual element value
# Access the element at row index 1 and column index 2

arr_2d[1, 2]

30

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>🔥 The more Pythonic way to access elements in a NumPy array is the second one, arr_2d[1, 2].🔥</strong></p>

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Slicing a 2D Array (Matrices)</p>

<a id="1.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

If you know how to select subsets of Python lists, you know most of what you need to know about ndarray slicing. The elements of the array being indexed that correspond to the elements of the indexing object are returned in a new array. The most important aspect of indexing is to remember that there is more than one dimension, and the indexing method should be able to handle these other dimensions.

<div style="display: flex; justify-content: left; gap: 10px;">
    <img src="https://i.ibb.co/64DGhj7/Numpy-index.jpg" width="500" height="200" alt="Numpy-index">
</div>

[SOURCE](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F16096753%2Fpython-array-slicing-how-can-2d-array-slicing-be-implemented&psig=AOvVaw0cHqeY-itYpRm19imsEBuR&ust=1644054927553000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCNiUt4vk5fUCFQAAAAAdAAAAABAD)

In [63]:
# 2D array slicing
print(arr_2d)

# Slice the array to get the first two rows and columns from index 1 onward
arr_2d[0:2, 1:]

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


array([[10, 15],
       [25, 30]])

In [64]:
# Shape bottom row

arr_2d[2]

array([35, 40, 45])

In [65]:
# Access the third row (index 2)

arr_2d[2, :]

array([35, 40, 45])

In [66]:
# Access all rows from the second column (index 1)

arr_2d[:, 1]

array([10, 25, 40])

In [67]:
# Let's remember our array

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
# Access all rows from the third column (index 2)

arr_2d[:, 2]

array([15, 30, 45])

In [69]:
# let's convert 25 to 55

# Update the element at row index 1 and column index 1
arr_2d[1, 1] = 55

# Display the array
arr_2d

array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [70]:
# default dtype is int. take a look at the assigning of the float value

# Update the element at row index 1 and column index 1
arr_2d[1][1] = 7.7

# Display the array
arr_2d

array([[ 5, 10, 15],
       [20,  7, 30],
       [35, 40, 45]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Fancy Indexing</p>

<a id="1.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

- Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once [SOURCE](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html#:~:text=Fancy%20indexing%20is%20conceptually%20simple,random.). In Fancy Indexing, we pass array of indices instead of single scalar(numbers) to fetch elements at different index points. Remember that the shape of the output depends on the shape of the index arrays rather than the shape of the array being indexed. [SOURCE01](https://www.google.com/url?sa=i&url=https%3A%2F%2Ftahamaddam.com%2Fcoding%2Fnumpy%2Fnumpy-fancy-indexing%2F&psig=AOvVaw3D06ReHkWL4NNeBSEHNddn&ust=1644055555472000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCPDY4bTm5fUCFQAAAAAdAAAAABAD), [SOURCE02](https://www.google.com/url?sa=i&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F52485840%2Fnumpy-fancy-indexing-with-tuples%3Frq%3D1&psig=AOvVaw3D06ReHkWL4NNeBSEHNddn&ust=1644055555472000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCPDY4bTm5fUCFQAAAAAdAAAAABAO), [VIDEO SOURCE](https://www.youtube.com/watch?v=WpXH4PzDtYA)

Fancy indexing allows you to **``select entire rows or columns out of order``**, to show this, let's quickly build out a numpy array:

In [71]:
# Create a 1D array with values from 0 to 30 with a step of 3
v = np.arange(0, 30, 3)

# Display the array
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

### **``Basic Indexing:``**
  - **``Definition``**: Basic indexing allows us to access individual elements or slices of an array using integers or slices.
  - **``Syntax``**: We use square brackets with the index of the element we want to access. For example, v[1] retrieves the element at index 1.
  - **``Zero-based Indexing``**: NumPy uses zero-based indexing, meaning that the first element is accessed with index 0, the second element with index 1, and so on.

In [72]:
# Access the element at index 1

v[1]

3

In [73]:
# Access the element at index 3

v[3]

9

In [74]:
# Access the element at index 7

v[7]

21

### **``Fancy Indexing:``**
  - **``Definition``**: Fancy indexing allows you to access specific elements of an array using arrays or lists of indices, rather than a single integer or slice.
  - **``Behavior``**: Fancy indexing returns a new array containing the elements at the specified indices. It does not modify the original array.
  - **``Flexibility``**: You can use lists, arrays, or any iterable of indices to retrieve elements from the original array.

In [75]:
# we can select separate elements using their indices in a list

# Define the list of indices
index_list=[1, 3, 7]

# Access the elements at the specified indices
v[index_list]

array([ 3,  9, 21])

In [76]:
# The double brackets indicate that we are passing a list or array of indices.

# Access the elements at the specified indices using double brackets
v[[1 ,3, 7]]

array([ 3,  9, 21])

Using double brackets for indexing achieves the same result as using a list or array of indices, and is still considered fancy indexing.
<hr>

In [77]:
# Create a 2D array of zeros with shape (10, 10) and integer type
arr2d = np.zeros((10, 10), dtype=int)

# Display the array
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [78]:
# Get the shape of the array

arr2d.shape

(10, 10)

In [79]:
# Length of array

# Get the number of rows (length of the first dimension)
length_arr = arr2d.shape[0]

# Print the number of rows
length_arr

10

In [80]:
# Access the first row (index 0)

arr2d[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
# Access the fourth row (index 3)

arr2d[3]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
# Fill each row with the corresponding index

for i in range(length_arr):
    arr2d[i]=i

# Display the modified array
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [83]:
# Access the fourth row (index 3)

arr2d[3]

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

**Now let's practice Fancy indexing; it allows the following:**

In [84]:
# we can select separate rows by indices in a list

# Access specific rows using fancy indexing
arr2d[[2, 4, 6, 8]]  # retrieves the rows at indices 2, 4, 6, and 8.

array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [85]:
# Allows in any order

# Access specific rows using fancy indexing
arr2d[[6, 4, 7, 2]]  # retrieves the rows at indices 6, 4, 7, and 2.

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

<h3>any_array[[row indices], [column indices]]</h3>

In [86]:
# Create a 1D array with values from 1 to 16 and reshape it into a 4x4 array

jj = np.arange(1, 17).reshape(4, 4)

In [87]:
# Display the array

jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [88]:
# let's select separate values of 5 and 12

# Access specific elements using fancy indexing
jj[[1, 2], [0, 3]]  # retrieves the values at row 1 and column 0 and row 2 and column 3.

array([ 5, 12])

In [89]:
# This time let's select separate values of 1, 10 and 16

# Access specific elements using fancy indexing
jj[[0, 2, 3], [0, 1, 3]]  # retrieves the values at row 0 and column 0, at row 2 and column 1, and row 3 and column 3.

array([ 1, 10, 16])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Using ***Basic Index*** & ***Fancy Index*** Together</p>

<a id="1.5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>



In [90]:
# Display the array

jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [91]:
# let's select "6" and "8" which are in the "same row" (index 1)

# Access specific elements using a combination of basic and fancy indexing
jj[1, [1, 3]]  # retrieves the values at row 1 and column 1 and row ` and column 3.

array([6, 8])

In [92]:
# let's select "2" and "14" which are the "same column" (index 1)

# Access specific elements using a combination of basic and fancy indexing
jj[[0, 3], 1]  # retrieves the values at row 0 and column 1 and row 3 and column 1.

array([ 2, 14])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Using ***Basic Slicing*** & ***Fancy Index*** Together</p>

<a id="1.6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


In [93]:
# Display the array

jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [94]:
# Let's first remember how normal slicing is executed

# Access specific rows and columns using basic slicing
jj[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [95]:
# let's select two middle columns

# Access specific columns using basic slicing and fancy indexing
jj[:, [1, 2]]   # retrieves all rows and only the second and third columns (indexing starts at 0).

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [96]:
# let's select center small square (4 elements)

# Access specific rows and columns using basic slicing and fancy indexing
jj[1:3, [1, 2]]

# Slicing selects rows 1 and 2 (the row at index 3 is NOT included) and retrieves the elements from columns 1 and 2.

array([[ 6,  7],
       [10, 11]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">More Indexing Help</p>

<a id="1.7"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>


Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

<div style="display: flex; justify-content: left; gap: 10px;">
    <img src="https://i.ibb.co/xmcGm9C/numpy-index1.png" width="600" height="200" alt="numpy-index1">
    <img src="https://i.ibb.co/bHYsGLb/numpy-indexing-1.png" width="400" height="200" alt="numpy-indexing-1">
</div>

<!-- ![image.png](https://i.ibb.co/xmcGm9C/numpy-index1.png) -->

[SOURCE](https://www.google.com/url?sa=i&url=https%3A%2F%2Fscipy-lectures.org%2Fintro%2Fnumpy%2Farray_object.html&psig=AOvVaw21eb1iMrmWndUhejWXLkY-&ust=1644056657663000&source=images&cd=vfe&ved=0CAwQjhxqFwoTCICAqr_q5fUCFQAAAAAdAAAAABAD)

Numpy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views. [SOURCE](http://cs-tklab.na-inet.jp/~tkouya/python/scipy-lectures/intro/numpy/array_object.html)

<!-- ![image-2.png](https://i.ibb.co/bHYsGLb/numpy-indexing-1.png) -->

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Selection on a Condition</p>

<a id="2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

- Let's briefly go over how to use brackets for selection based off of comparison operators.

In [97]:
# Create a 1D array with values from 1 to 10
arr = np.arange(1, 11)

# Display the array
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
# Create a boolean array indicating which elements are greater than 4

arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [101]:
# Create a boolean array indicating which elements are greater than 4

bool_arr = arr > 4

In [102]:
# Use the boolean array to filter the original array

arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [103]:
# Use boolean indexing to filter the array for elements less than 6 DIRECTLY

arr[arr < 6]

array([1, 2, 3, 4, 5])

In [104]:
# Use boolean indexing to filter the array for elements greater than 2 DIRECTLY

arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
# Create a boolean array indicating which elements are NOT equal to 3 and NOT equal to 4

(arr != 3) & (arr != 4)

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [106]:
# and ==> &

# Use boolean indexing to filter the array for elements NOT equal to 3 and NOT equal to 4
arr[(arr != 3) & (arr != 4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])

In [107]:
# if you want you can use if_statement and for_loop

# Initialize an empty list to hold the filtered elements
con_arr = []

# Loop through each element in arr
for i in arr:
    if (i != 3) & (i != 4):
        con_arr.append(i)
print(con_arr)

[1, 2, 5, 6, 7, 8, 9, 10]


## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Broadcasting</p>

<a id="3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Numpy arrays differ from a normal Python list because of their ability to broadcast [SOURCE](https://numpy.org/doc/stable/user/theory.broadcasting.html).<br>

**``Broadcasting``** is the name given to the method that NumPy uses to allow array arithmetic between arrays with a different shape or size [SOURCE](https://machinelearningmastery.com/broadcasting-with-numpy-arrays/#:~:text=Broadcasting%20is%20the%20name%20given,a%20different%20shape%20or%20size.&text=Subject%20to%20certain%20constraints%2C%20the,that%20they%20have%20compatible%20shapes.).<br>

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is **``broadcast``** across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation [SOURCE](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html).<br>

Broadcasting is an operation of matching the dimensions of differently shaped arrays in order to be able to perform further operations on those arrays (eg per-element aritmetic) [SOURCE01](https://towardsdatascience.com/broadcasting-in-numpy-58856f926d73), [SOURCE02](https://towardsdatascience.com/a-numpy-affair-broadcasting-ead20d9661f).<br>

**NumPy Broadcasting Limitations**<br>
Broadcasting is a very easy and handy tool when working with Numpy arrays. Although, there are many rules and restrictions to perform the operations.

There are constraints on the dimension and shape of the arrays. We can perform broadcasting in cases where both the arrays have the same shape or only if either of the two has a size of 1. Also, we have to consider the dimensions in reverse order. We count it from the trailing dimension [SOURCE](https://data-flair.training/blogs/numpy-broadcasting/).<br>

Be informed about the discussion on [When broadcasting is a bad idea? (numpy)](https://stackoverflow.com/questions/47309818/when-broadcasting-is-a-bad-idea-numpy) at Stackoverflow.

More Sources: [SOURCE01](https://inblog.in/Broadcasting-in-Numpy-A-Complete-Guide-jfKy2vzHiY), [SOURCE02](https://www.pluralsight.com/guides/broadcasting-numpy-arrays-arithmeetic-operations), [SOURCE03](https://www.geeksforgeeks.org/python-broadcasting-with-numpy-arrays/), [SOURCE04](https://www.askpython.com/python-modules/numpy/numpy-broadcasting), [SOURCE05](https://stackoverflow.com/questions/32832923/numpy-what-is-broadcasting), [SOURCE06](https://stackoverflow.com/questions/61090539/how-can-i-use-broadcasting-with-numpy-to-speed-up-this-correlation-calculation), [SOURCE07](https://stackoverflow.com/questions/68185016/numpy-broadcasting-two-arrays-of-different-shape-to-matrix), [SOURCE08](https://stackoverflow.com/questions/50569344/broadcasting-using-numpys-sum-function)

In [108]:
# Let us remember our arr

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
# Correctly assign the value 77 to the first five elements (Broadcasting)
arr[:5] = 77

# Display the array
arr

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [110]:
# What about broadcating on a Python list

# Create a list of even numbers from 0 to 10
a = [0, 2, 4, 6, 8, 10]

# Display the list
a

[0, 2, 4, 6, 8, 10]

In [111]:
# a[0:3] = 100 # gives an error of "TypeError: can only assign an iterable"

TypeError: can only assign an iterable

### 🔥 Be Careful: 🔥

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 The expression above gives an error because we are trying to assign a single integer value (100) to a slice of a list, which expects an iterable (like a list or another sequence) of the same length ❗❗❗</strong></p>

In [112]:
# Replace the first three elements with 100 in the list

a[:3] = [100, 100, 100]

# Display the modified list
a

[100, 100, 100, 6, 8, 10]

In [113]:
# Let us reset our array, we'll see why we had to reset in  a moment

# Create a 1D array with values from 0 to 10
arr = np.arange(0, 11)

# Display the array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [114]:
# Display original array
display(arr)

# Create a slice of the array from index 0 to 5
slice_of_arr = arr[0:6]

# Display the slice
slice_of_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([0, 1, 2, 3, 4, 5])

In [115]:
# Display original array
display(arr)

# Display sliced array
display(slice_of_arr)

# Assign the value 99 to all elements of the sliced array
slice_of_arr[:] = 99

# Display the Slice again
display(slice_of_arr)

# Display original array
# The changes are reflected to the original array.
display(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([0, 1, 2, 3, 4, 5])

array([99, 99, 99, 99, 99, 99])

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>📢 Now note that the changes also occur in our original array❗❗❗</strong></p>

That's an important aspect of how slicing works in NumPy! When you create a slice of a NumPy array, that **``slice is a view of the original array``** **``rather than a separate copy``**. This means that **``any changes made to the slice will also affect the original array``**. Data is NOT copied, it's a view of the original array! This avoids memory problems!


<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#008000; font-size:125%; text-align:left;"><strong>📢View vs. Copy:</strong></p>

When you slice a NumPy array, you get a view of the original data. This means that both the original array and the slice **``share the same underlying data in memory``**.
Changes made to the slice will be reflected in the original array.

- **``Original Array``**: The variable **``arr``** contains the **``integers from 0 to 10``**.
- **``Slicing``**: The variable **``slice_of_arr``** is a slice of arr, containing the **``first six elements``**.
- **``Modification``**: The line **``slice_of_arr[:] = 99``** updates **``all elements in the slice to 99``**.
- **``Final Display``**: After modification, displaying **``slice_of_arr``** and **``arr``** will show the updated values.

<hr>

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#0000FF; font-size:120%; text-align:left;"><strong>🤔💭 However we sometimes need the original data throughout our analysis and do NOT want to lose is. So, how to prevent this operation❓</strong></p>

To prevent changes made to a slice from affecting the original array, we can create **``a copy of the array``** using the **``.copy()``** method. This way, any modifications we make to the copy will NOT impact the original data. Here's how you can do it:

In [116]:
# To get a copy, need to be explicit

# Create a copy of the array
arr_copy = arr.copy()

# Print the copied array
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [117]:
# Assign new values to the first six elements of arr_copy

arr_copy[:6] = [0, 1, 2, 3, 4, 5]

In [118]:
# Print the modified array

arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
# Print the original array. NO CHANGES ON THE ORIGINAL ARRAY

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Operations</p>

<a id="4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

<!-- ![image.png](https://i.ibb.co/n65mpTL/numpy-operations.png) -->

<div style="display: flex; justify-content: left; gap: 10px;">
    <img src="https://i.ibb.co/n65mpTL/numpy-operations.png" width="700" height="200" alt="numpy-operations">
</div>

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Arithmetic Operations</p>

<a id="4.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

- You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [120]:
# Create a 1D array with values from 0 to 9
arr = np.arange(0, 10)

# Print the array
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
# Print the array
display(arr)

# Perform element-wise ADDITION
arr + arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [122]:
# Print the array
display(arr)

# Perform element-wise MULTIPLICATION
arr * arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [123]:
# Print the array
display(arr)

# Perform element-wise SUBTRACTION
arr - arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [124]:
# Warning on division by zero, but NOT give an error!
# Just replaced with "nan"

# Print the array
display(arr)

# Perform element-wise DIVISION
arr / arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

C:\Users\hp\AppData\Local\Temp\ipykernel_4244\2015019205.py:8: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [125]:
# Also warning, but not an error instead infinity

# Print the array
display(arr)

# Perform element-wise DIVISION
1/arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

C:\Users\hp\AppData\Local\Temp\ipykernel_4244\2996930040.py:7: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [126]:
# Print the array
display(arr)

# Perform element-wise squaring
arr**2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [127]:
# Print the array
display(arr)

# Perform element-wise SUBTRACTION
arr-2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [128]:
# Print the array
display(arr)

# Perform element-wise ADDITION
arr+1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [129]:
# Print the array
display(arr)

# Scale the array elements by 1/2
arr*1/2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Universal Array Functions</p>

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [130]:
# Let's remember our original array

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
# Perform element-wise SUBTRACTION

np.subtract(arr, 1)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [132]:
# Perform element-wise ADDITION

np.add(arr, 2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [133]:
# Perform element-wise DIVISION

np.divide(arr, 2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [134]:
# Perform element-wise MULTIPLICATION

np.multiply(arr, 4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [135]:
# Compute the cube of each element

np.power(arr, 3)  # v**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [136]:
# Compute the modulus of each element with respect to 2

np.mod(arr, 2)  # v % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [137]:
# Compute the absolute value of -9

np.absolute(-9)

9

In [138]:
# Compute the absolute multiple values of -3, -5, 4, 6

np.absolute([-3, -5, 4, 6])

array([3, 5, 4, 6])

In [139]:
# Compute the absolute values of the array

np.absolute(np.array([-3, -5, 4, 6]))

array([3, 5, 4, 6])

In [140]:
# Create a 3x3 array with values from 0 to 8
x1 =np.arange(9.0).reshape(3, 3)

# Create a 1D array with floating point values from 0. to 2.
x2 = np.arange(3.0)

In [141]:
# Display the array "x1"

x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [142]:
# Display the array "x2"

x2

array([0., 1., 2.])

In [143]:
# Perform element-wise SUBTRACTION

np.subtract(x1, x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [144]:
# Compute the square root of each element

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [145]:
# Compute the exponential (e^) of each element

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [146]:
# Same as arr.max()

# Compute the maximum value in the array
np.max(arr)

9

**There are many trigonometric functions:**

In [147]:
# Compute the sine of each element

np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [148]:
# Compute the sine of pi/2

np.sin(np.pi/2)

1.0

In [149]:
# Compute the tangent of pi/4

np.tan(np.pi/4)

0.9999999999999999

In [150]:
# Compute the natural logarithm of each element

np.log(arr)

C:\Users\hp\AppData\Local\Temp\ipykernel_4244\985143704.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [151]:
# Compute the base-10 logarithm of 1000

np.log10(1000)

3.0

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Statistical Calculations</p>

<a id="4.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

Statistics is concerned with collecting and then analyzing that data. It includes methods for collecting the samples, describing the data, and then concluding that data. NumPy is the fundamental package for scientific calculations and hence goes hand-in-hand for NumPy statistical Functions.

NumPy contains various statistical functions that are used to perform statistical data analysis. These statistical functions are useful when finding a maximum or minimum of elements. It is also used to find basic statistical concepts like standard deviation, variance, etc.

NumPy is equipped with the following statistical functions:

**``np.amin(arr)``** This function determines the minimum value of the element along a specified axis.<br>
**``np.amax(arr)``** This function determines the maximum value of the element along a specified axis.<br>
**``arr.min()``** Returns minimum value of arr<br>
**``arr.max(axis=0)``** Returns maximum value of specific axis<br>
**``np.mean(arr, axis=0)``** It determines the mean value of the data set.<br>
**``np.median(arr)``** It determines the median value of the data set.<br>
**``np.std(arr, axis=1)``** It determines the standard deviation.<br>
**``np.var(arr)``** It determines the variance.<br>
**``np.ptp(arr)``** It returns a range of values (maximum - minimum) along an axis.<br>
**``np.average(arr)``** It determines the weighted average.<br>
**``np.percentile(arr)``** It determines the nth percentile of data along the specified axis.<br>
**``np.corrcoef(arr)``** Returns correlation coefficient of array

More Sources: [SOURCE01](https://data-flair.training/blogs/numpy-statistical-functions/), [SOURCE02](https://python-tricks.com/statistical-functions-in-numpy/), [SOURCE03](https://numpy.org/doc/stable/reference/routines.statistics.html), [SOURCE04](https://www.tutorialspoint.com/numpy/numpy_statistical_functions.htm), [SOURCE05](https://www.i2tutorials.com/numpy-tutorial/numpy-statistical-functions/), [SOURCE06](https://towardsdatascience.com/use-numpy-for-statistics-and-arithmetic-operations-in-2020-2e157b784df4), [SOURCE07](https://cloudxlab.com/assessment/displayslide/2509/numpy-mathematical-and-statistical-functions-on-numpy-arrays), [SOURCE08](https://stackoverflow.com/questions/63888139/calculating-some-statistics-for-each-column-of-a-numpy-ndarray), [SOURCE09](https://www.codecademy.com/learn/intro-statistics-numpy)

In [152]:
# Create a 1D NumPy array with the specified values
v = np.array([1, 1, 2, 2, 3, 3, 3])

# Display the array
v

array([1, 1, 2, 2, 3, 3, 3])

In [153]:
# Calculate the mean using np.mean

np.mean(v)

2.142857142857143

In [154]:
# Calculate the mean using v.mean()

v.mean()

2.142857142857143

In [155]:
# Calculate the median using np.median

np.median(v)

2.0

In [156]:
# Calculate the median using np.percentile

np.percentile(v, 50)

2.0

In [ ]:
# v.median()  # it gives an AttributeError: 'numpy.ndarray' object has no attribute 'median'

### 🔥 Be Careful: 🔥

<p style="background-color:#FFFFFF; font-family:newtimeroman; color:#FF0000; font-size:125%; text-align:left;"><strong>📢❗🚨 The reason you encounter an AttributeError when calling v.median() is that the median() method is NOT a direct attribute of NumPy arrays. Instead, you should use the np.median() function to compute the median of the array. ❗❗❗</strong></p>

In [157]:
# Compute the standard deviation of the array

v.std()

0.8329931278350429

In [158]:
# Compute the variance of the array

v.var()

0.6938775510204082

In [159]:
# Compute the sum of the array

v.sum()

15

In [160]:
# Compute the minimum value in the array

v.min()

1

In [161]:
# Compute the peak-to-peak value

np.ptp(v) # pick to pick. It's the range of values (maximum - minimum) along an axis.

2

In [162]:
# Set the random seed for reproducibility
np.random.seed(42)

# Generate a 3x5 array of random numbers from a standard normal distribution
xarr = np.random.randn(3, 5)

# Display the array
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004],
       [-0.46341769, -0.46572975,  0.24196227, -1.91328024, -1.72491783]])

In [163]:
# Compute the correlation coefficients

np.corrcoef(xarr)

array([[ 1.        , -0.72342114, -0.20484812],
       [-0.72342114,  1.        ,  0.46728036],
       [-0.20484812,  0.46728036,  1.        ]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Official Tutorial</p>

<a id="5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.

<a id="6"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#E51A59; font-size:150%; text-align:center; border-radius:10px 10px;">End of the NumPy Session - 02</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>


<br><br><br>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>