<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>

<hr>

<a href="https://lms.clarusway.com/mod/lesson/view.php?id=2463&pageid=4531&startlastseen=no"><img align="center" src="https://i.ibb.co/6Z5pQxD/lmss.png" alt="Open in Clarusway LMS" width="70" height="200" title="Open Clarusway Learning Management Sytem"></a>

<a href="https://github.com/clarusway/DS-DE-0322-Students/blob/main/3-%20Classes%26Labs/2-DAwPY/DAwPy_S01_(Numpy_Arrays).ipynb"><img align="left" src="https://i.ibb.co/n3HWyQX/github-logo.png" alt="Open in Clarusway GitHub" width="90" height="150" title="Open and Execute in Clarusway GitHub Repository"></a>

<a href="https://nbviewer.org/github/4dsolutions/clarusway_data_analysis/blob/main/DAwPy_S1_%28Numpy_Arrays%29/DAwPy_S1_%28Numpy_Arrays%29.ipynb"><img align="right" src="https://i.ibb.co/48wtV8c/nbviewer-badge.png" alt="Open in nbviewer" width="100" height="100" title="Open and Execute in nbviewer"></a><br/>

<hr>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="500" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="text-align: center;"><img src="https://i.ibb.co/XS0bxSH/best-bootcamps.png" width="300" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY_Courses"></p>

<p style="text-align: center;"><img src=https://i.ibb.co/8NdjfdZ/Num-Py-logo.png width="500" height="200">

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:150%; text-align:center; border-radius:10px 10px;">Session - 01</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#E51A59; font-size:150%; text-align:center; border-radius:10px 10px;">Numpy Arrays (Session-01 - Part-02)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [WHY NUMPY? & WHY DO WE NEED IT?](#0)
    * [When you make a change to an array, it becomes another object.](#0.1)
    * [Advanced mathematical operations are executed more efficientl](#0.2)
    * [Comparing list and array by ids](#0.3)
    * [Comparing list and array by size](#0.4)
    * [Comparing list and array by computation time](#0.5)
* [THE END OF THE SESSION-01 (PART-02)](#1)

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Why Numpy? & Why Do We Need It?</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

**There are several important differences between NumPy arrays and the standard Python sequences:**

- **``NumPy arrays``** have a ``fixed size`` at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a **``NumPy array``** are all required to be of ``the same data type``, and thus will be the ``same size in memory``. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- **``NumPy arrays``** facilitate ``advanced mathematical and other types of operations`` on large numbers of data. Typically, such operations are executed more efficiently and ``with less code`` than is possible using Python's built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today's scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

<img src=https://i.ibb.co/2FD1VMM/Numpy-vs-Lists.pngg width="500" height="200">

[Numpy Array vs List Source 01](https://blog.finxter.com/what-are-advantages-of-numpy-over-regular-python-lists/),
[Numpy Array vs List Source 02](https://numpy.org/doc/stable/user/whatisnumpy.html),
[Numpy Array vs List Source 03](https://python.plainenglish.io/python-list-vs-numpy-array-whats-the-difference-7308cd4b52f6),
[Numpy vs List Source 04](https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference#:~:text=A%20numpy%20array%20is%20a,a%20tuple%20of%20nonnegative%20integers.&text=A%20list%20is%20the%20Python,contain%20elements%20of%20different%20types.),
[Numpy Array vs List Source 05](https://dev.to/chanduthedev/python-list-vs-numpy-array-3pjp),
[Numpy Array vs List Source 06](https://medium.com/analytics-vidhya/list-vs-numpy-comparision-35bf921588e9),
[Numpy Array vs List Source 07](https://stackoverflow.com/questions/15944171/python-differences-between-lists-and-numpy-array-of-objects),
[Numpy Array vs List Video Source 01](https://www.youtube.com/watch?v=mkbgEvUkSaM),
[Numpy Array vs List Video Source 02](https://www.youtube.com/watch?v=JtW_xGNDEJ8),
[Numpy Array vs List Video Source 03](https://www.youtube.com/watch?v=C10KmAbCW6A)

In [ ]:
import numpy as np
import time
import sys

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">When you make a change to an array, it becomes another object!</p>

<a id="0.1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [39]:
my_list = [1, 2, 3, 4, 5]

my_first_array = np.array(my_list)
my_first_array

array([1, 2, 3, 4, 5])

In [40]:
id(my_first_array)  # this is the location of my_first_array in memory.

1410958507440

In [41]:
my_first_array = np.append(my_first_array, (6, 7))  # the location of array changed.
                                                    # the original one deleted, a different new array object now.

id(my_first_array)

1410977658704

**let's look at the same situation for the lists in Python:**

In [42]:
id(my_list)  # this is the location of my_list in memory.

1410977501568

In [43]:
my_list.append([6, 7])  # we have added some values to the list.
my_list

[1, 2, 3, 4, 5, [6, 7]]

In [44]:
id(my_list)  # Be noted! The location of my_list didn't change.
             # Unlike numpy arrays, it is still the same object!

1410977501568

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Advanced mathematical operations are executed more efficiently</p>

<a id="0.2"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [45]:
list_a = [1, 2, 3, 4]
list_b = [2, 3, 4, 5]

In [46]:
# a * b # Gives an error

NameError: name 'a' is not defined

In [47]:
a_mult_b = []

for i in range(len(list_a)) :
    a_mult_b.append(list_a[i] * list_b[i])

a_mult_b

[2, 6, 12, 20]

**let's do the same in the numpy arrays:**

In [48]:
a_arr = np.array(list_a)
b_arr = np.array(list_b)

In [49]:
a_arr * b_arr

array([ 2,  6, 12, 20])

In [50]:
a_arr

array([1, 2, 3, 4])

**Another example:**

In [51]:
arr_1 = np.array([[1, 2, 3, 4], [1, 2, 3, 4], [2, 3, 4, 5]])
arr_2 = np.array([[2, 3, 4, 5], [1, 2, 4, 5], [1, 2, 3, 4]])

In [52]:
arr_1

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [2, 3, 4, 5]])

In [53]:
arr_2

array([[2, 3, 4, 5],
       [1, 2, 4, 5],
       [1, 2, 3, 4]])

In [54]:
arr_1 * arr_2

array([[ 2,  6, 12, 20],
       [ 1,  4, 12, 20],
       [ 2,  6, 12, 20]])

### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Comparing list and array by ids</p>

<a id="0.3"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [55]:
print(list_a)
id(list_a)

[1, 2, 3, 4]


1410978765056

In [56]:
print(list_b)
id(list_b)

[2, 3, 4, 5]


1410976582208

In [57]:
id(list_a) == id(list_b)

False

In [58]:
list_c = list_a[:]

print(list_a)
print(list_c)

id(list_a) == id(list_c)

[1, 2, 3, 4]
[1, 2, 3, 4]


False

In [59]:
list_c = list_a

id(list_a) == id(list_c)

True

In [60]:
print(list_a)

print(id(list_a))
print(id(list_a[0]))
print(id(list_a[1]))
print(id(list_a[2]))
print(id(list_a[0]) == id(list_a[1]) == id(list_a[2]))

[1, 2, 3, 4]
1410978765056
140719622886184
140719622886216
140719622886248
False


In [61]:
print(arr_1)

print(id(arr_1))
print(id(arr_1[0]))
print(id(arr_1[1]))
print(id(arr_1[2]))
print(id(arr_1[0]) == id(arr_1[1]) == id(arr_1[2]))

[[1 2 3 4]
 [1 2 3 4]
 [2 3 4 5]]
1410982971120
1410989243728
1410989243728
1410989243728
True


### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Comparing list and array by size</p>

<a id="0.4"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [62]:
sys.getsizeof(5)  # Returns the size of object in bytes.

28

In [63]:
sys.getsizeof(99999999)

28

In [65]:
sys.getsizeof("b")

50

In [66]:
sys.getsizeof("alidelveli")

59

In [67]:
numbers = range(1000)

print("size of one item in list :", sys.getsizeof(numbers[1]))  # sys.getsizeof() returns the memory size of the object
print("size of all items in list :", sys.getsizeof(numbers[1]) * len(numbers))

print("---" * 10)

arr = np.arange(1000)

print("size of one item in array :", arr.itemsize)  # itemsize() returns the length of one array element in bytes.
print("size of all items in array :", arr.itemsize * arr.size)

size of one item in list : 28
size of all items in list : 28000
------------------------------
size of one item in array : 4
size of all items in array : 4000


### <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:150%; text-align:LEFT; border-radius:10px 10px;">Comparing list and array by computation time</p>

<a id="0.5"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [68]:
time.time()  # Return the current time in seconds since the Epoch.

1728551660.7434223

In [69]:
start = time.time()  # Assigning the current epoch time to the "start" variable
start

1728551669.3653455

In [70]:
# Wait for several seconds and than run this cell.

time.time() - start  # time difference between two operations

16.656564474105835

In [71]:
size = 1000000

items1 = range(size)

items2 = range(size)

a1 = np.arange(size)

a2 = np.arange(size)

start = time.time()

result = [(x+y) for x, y in zip(items1, items2)]
print("python list took : ", (time.time() - start) * 1000)

start = time.time()
result = a1 + a2
print("numpy array took :", (time.time()-start) * 1000)

python list took :  338.49024772644043
numpy array took : 40.62843322753906


<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#E51A59; font-size:150%; text-align:center; border-radius:10px 10px;">End of the NumPy Session-01 (Part-02)</p>

<p style="text-align: center;"><img src="https://i.ibb.co/99DQ3TY/DS-Courses.png" class="img-fluid" 
alt="CLRSWY"></p>


<br><br><br>

<p style="text-align: center;"><img src="https://i.ibb.co/Rpz9L36/clarusway-logo-black.png" width="450" height="200" class="img-fluid" alt="CLRSWY_LOGO"></p>

<p style="background-color:#E51A59; font-family:newtimeroman; color:#FDFEFE; font-size:130%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

<a href="https://clarusway.com/contact-us/"><img align="center" src="https://i.ibb.co/B43qn24/officially-licensed-logo.png" alt="Open in Clarusway LMS" width="110" height="200" title="This notebook is licensed by Clarusway IT training school. Please contact the authorized persons about the conditions under which you can use or share."></a>